# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stylesheet/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 295)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(36, 31, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 31, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        MainWindow.setPalette(palette)
        self.input_url = QtWidgets.QLineEdit(MainWindow)
        self.input_url.setGeometry(QtCore.QRect(60, 130, 331, 25))
        self.input_url.setObjectName("input_url")
        self.link_txt = QtWidgets.QLabel(MainWindow)
        self.link_txt.setGeometry(QtCore.QRect(9, 136, 28, 17))
        self.link_txt.setObjectName("link_txt")
        self.save_txt = QtWidgets.QLabel(MainWindow)
        self.save_txt.setGeometry(QtCore.QRect(9, 174, 50, 17))
        self.save_txt.setObjectName("save_txt")
        self.input_save = QtWidgets.QLineEdit(MainWindow)
        self.input_save.setGeometry(QtCore.QRect(60, 170, 261, 25))
        self.input_save.setObjectName("input_save")
        self.btnDownload = QtWidgets.QPushButton(MainWindow)
        self.btnDownload.setGeometry(QtCore.QRect(170, 250, 80, 25))
        self.btnDownload.setObjectName("btnDownload")
        self.mp3_option = QtWidgets.QRadioButton(MainWindow)
        self.mp3_option.setGeometry(QtCore.QRect(110, 200, 112, 23))
        self.mp3_option.setChecked(True)
        self.mp3_option.setObjectName("mp3_option")
        self.mp4_option = QtWidgets.QRadioButton(MainWindow)
        self.mp4_option.setGeometry(QtCore.QRect(250, 200, 112, 23))
        self.mp4_option.setObjectName("mp4_option")
        self.btnSelect = QtWidgets.QPushButton(MainWindow)
        self.btnSelect.setGeometry(QtCore.QRect(328, 170, 71, 25))
        self.btnSelect.setObjectName("btnSelect")
        self.logo = QtWidgets.QLabel(MainWindow)
        self.logo.setGeometry(QtCore.QRect(40, 0, 341, 131))
        self.logo.setObjectName("logo")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YTdownloader"))
        self.link_txt.setText(_translate("MainWindow", "Link"))
        self.save_txt.setText(_translate("MainWindow", "Save as"))
        self.btnDownload.setText(_translate("MainWindow", "Download"))
        self.mp3_option.setText(_translate("MainWindow", "mp3"))
        self.mp4_option.setText(_translate("MainWindow", "mp4"))
        self.btnSelect.setText(_translate("MainWindow", "Select"))
        self.logo.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"stylesheet/yt_downloader.png\" /></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
